import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { access, cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const EXTENSION_ROOT = path.join(ROOT, "extension");
export const VARIANTS_ROOT = path.join(ROOT, "variants");
export const BUILD_ROOT = path.join(ROOT, "build");
export const DIST_ROOT = path.join(ROOT, "dist");
export const VARIANT_IDS = Object.freeze(["chrome", "chromium-gost"]);

async function readJson(file) {
  return JSON.parse(await readFile(file, "utf8"));
}

function requireText(value, label) {
  if (typeof value !== "string" || !value.trim()) {
    throw new Error(`${label} must be a non-empty string`);
  }
}

function requireInteger(value, label, minimum = 0) {
  if (!Number.isInteger(value) || value < minimum) {
    throw new Error(`${label} must be an integer >= ${minimum}`);
  }
}

export function resolveVariantIds(selector = "all") {
  if (selector === "all") return [...VARIANT_IDS];
  if (!VARIANT_IDS.includes(selector)) {
    throw new Error(`Unknown variant "${selector}"; expected ${VARIANT_IDS.join(", ")} or all`);
  }
  return [selector];
}

export async function loadVariant(id) {
  const configPath = path.join(VARIANTS_ROOT, id, "config.json");
  const config = await readJson(configPath);
  if (config.id !== id) throw new Error(`${configPath}: id must be "${id}"`);

  for (const [label, value] of [
    ["browserLabel", config.browserLabel],
    ["archiveName", config.archiveName],
    ["manifest.name", config.manifest?.name],
    ["manifest.version", config.manifest?.version],
    ["manifest.versionName", config.manifest?.versionName],
    ["manifest.minimumChromeVersion", config.manifest?.minimumChromeVersion],
    ["manifest.description", config.manifest?.description],
    ["manifest.actionTitle", config.manifest?.actionTitle],
    ["popup.title", config.popup?.title],
    ["popup.brand", config.popup?.brand],
  ]) {
    requireText(value, `${id}.${label}`);
  }

  if (!/^\d+(?:\.\d+){0,3}$/.test(config.manifest.version)) {
    throw new Error(`${id}.manifest.version must use Chromium's numeric version format`);
  }
  if (!config.archiveName.endsWith(`-${config.manifest.version}.zip`)) {
    throw new Error(`${id}.archiveName must include its manifest version`);
  }

  const native = config.nativeDownloads || {};
  for (const key of [
    "startTimeoutMs",
    "completionTimeoutMs",
    "controlSettleMs",
    "lateRecoveryGraceMs",
    "interItemDelayMs",
    "matchWindowMs",
  ]) {
    requireInteger(native[key], `${id}.nativeDownloads.${key}`);
  }
  requireInteger(native.maxAttempts, `${id}.nativeDownloads.maxAttempts`, 1);
  if (native.completionTimeoutMs < native.startTimeoutMs) {
    throw new Error(`${id}: completion timeout must cover the start timeout`);
  }
  if (native.matchWindowMs < native.startTimeoutMs + native.lateRecoveryGraceMs) {
    throw new Error(`${id}: match window must cover start timeout plus late-recovery grace`);
  }

  await access(path.join(VARIANTS_ROOT, id, "INSTALL.txt"));
  return config;
}

export function publicVariantConfig(config) {
  return {
    id: config.id,
    browserLabel: config.browserLabel,
    popupTitle: config.popup.title,
    popupBrand: config.popup.brand,
    nativeDownloads: config.nativeDownloads,
  };
}

function variantScript(config) {
  const serialized = JSON.stringify(publicVariantConfig(config), null, 2);
  return `/** Generated by scripts/build.mjs. Do not edit. */\n(function () {\n  const deepFreeze = (value) => {\n    if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;\n    for (const child of Object.values(value)) deepFreeze(child);\n    return Object.freeze(value);\n  };\n  globalThis.LEXPACK_VARIANT = deepFreeze(${serialized});\n})();\n`;
}

function buildManifest(base, config) {
  return {
    manifest_version: base.manifest_version,
    name: config.manifest.name,
    version: config.manifest.version,
    version_name: config.manifest.versionName,
    minimum_chrome_version: config.manifest.minimumChromeVersion,
    description: config.manifest.description,
    permissions: base.permissions,
    host_permissions: base.host_permissions,
    action: {
      ...base.action,
      default_title: config.manifest.actionTitle,
    },
    background: base.background,
    content_scripts: base.content_scripts,
    icons: base.icons,
  };
}

export async function buildVariant(id) {
  const config = await loadVariant(id);
  const target = path.join(BUILD_ROOT, id);
  const baseManifest = await readJson(path.join(EXTENSION_ROOT, "manifest.base.json"));

  await rm(target, { recursive: true, force: true });
  await mkdir(target, { recursive: true });
  await cp(EXTENSION_ROOT, target, {
    recursive: true,
    filter(source) {
      const name = path.basename(source);
      return name !== "manifest.base.json" && name !== ".DS_Store";
    },
  });

  const manifest = buildManifest(baseManifest, config);
  await writeFile(path.join(target, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  await writeFile(
    path.join(target, "shared", "variant-config.js"),
    variantScript(config)
  );
  await cp(path.join(VARIANTS_ROOT, id, "INSTALL.txt"), path.join(target, "INSTALL.txt"));
  await writeFile(
    path.join(target, "BUILD-INFO.json"),
    `${JSON.stringify(
      {
        schemaVersion: 1,
        variant: id,
        browser: config.browserLabel,
        version: config.manifest.version,
        versionName: config.manifest.versionName,
      },
      null,
      2
    )}\n`
  );

  return { config, manifest, target };
}

function manifestReferences(manifest) {
  return [
    manifest.background?.service_worker,
    manifest.action?.default_popup,
    ...Object.values(manifest.action?.default_icon || {}),
    ...Object.values(manifest.icons || {}),
    ...(manifest.content_scripts || []).flatMap((entry) => entry.js || []),
  ].filter(Boolean);
}

export async function checkBuiltVariant(id) {
  const config = await loadVariant(id);
  const target = path.join(BUILD_ROOT, id);
  const manifest = await readJson(path.join(target, "manifest.json"));

  const expected = {
    name: config.manifest.name,
    version: config.manifest.version,
    version_name: config.manifest.versionName,
    minimum_chrome_version: config.manifest.minimumChromeVersion,
  };
  for (const [key, value] of Object.entries(expected)) {
    if (manifest[key] !== value) {
      throw new Error(`${id}: manifest.${key} is ${JSON.stringify(manifest[key])}, expected ${JSON.stringify(value)}`);
    }
  }
  if (manifest.manifest_version !== 3) throw new Error(`${id}: manifest_version must be 3`);
  if (!manifest.content_scripts?.[0]?.js?.includes("shared/variant-config.js")) {
    throw new Error(`${id}: variant config must load before shared runtime code`);
  }
  for (const reference of manifestReferences(manifest)) {
    await access(path.join(target, reference));
  }

  const generatedConfig = await readFile(
    path.join(target, "shared", "variant-config.js"),
    "utf8"
  );
  if (generatedConfig !== variantScript(config)) {
    throw new Error(`${id}: generated variant config is stale`);
  }
  await access(path.join(target, "INSTALL.txt"));
  await access(path.join(target, "BUILD-INFO.json"));
  return { config, manifest, target };
}

function run(command, args, cwd = ROOT) {
  const result = spawnSync(command, args, { cwd, encoding: "utf8" });
  if (result.status !== 0) {
    throw new Error(
      `${command} ${args.join(" ")} failed\n${result.stdout || ""}${result.stderr || ""}`
    );
  }
}

export async function packageVariant(id) {
  const built = await buildVariant(id);
  await checkBuiltVariant(id);
  await mkdir(DIST_ROOT, { recursive: true });
  const archivePath = path.join(DIST_ROOT, built.config.archiveName);
  await rm(archivePath, { force: true });
  run("zip", ["-q", "-r", "-X", archivePath, "."], built.target);
  run("unzip", ["-tq", archivePath]);
  const bytes = await readFile(archivePath);
  return {
    variant: id,
    browser: built.config.browserLabel,
    version: built.config.manifest.version,
    versionName: built.config.manifest.versionName,
    file: built.config.archiveName,
    sha256: createHash("sha256").update(bytes).digest("hex"),
  };
}

export async function writeReleaseIndex(artifacts) {
  await mkdir(DIST_ROOT, { recursive: true });
  const index = { schemaVersion: 1, artifacts };
  await writeFile(
    path.join(DIST_ROOT, "release-index.json"),
    `${JSON.stringify(index, null, 2)}\n`
  );
  await writeFile(
    path.join(DIST_ROOT, "SHA256SUMS"),
    `${artifacts.map((item) => `${item.sha256}  ${item.file}`).join("\n")}\n`
  );
}
